#!/usr/bin/env bash
set -Eeuo pipefail

# Build txgbe module against a given kernel tree via kbuild.
#
# Usage:
#   tools/build_one.sh /path/to/kernel/tree-or-build
#
# Environment:
#   ARCH, CROSS_COMPILE, LLVM, CC, KCFLAGS, EXTRA_CFLAGS, V, JOBS
#
# Notes:
# - The kernel tree must be prepared for external modules (at least
#   "make modules_prepare" or a headers tree that already contains
#   include/generated/autoconf.h).

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
MOD_DIR="${REPO_ROOT}/src"

KERNELDIR="${1:-${KERNELDIR:-}}"
if [[ -z "${KERNELDIR}" ]]; then
  echo "Usage: $0 /path/to/kernel/tree-or-build" >&2
  echo "Or set KERNELDIR=/path/to/kernel/tree-or-build" >&2
  exit 2
fi

if [[ ! -d "${KERNELDIR}" ]]; then
  echo "Error: KERNELDIR does not exist: ${KERNELDIR}" >&2
  exit 2
fi

# Basic sanity checks: we need kernel headers and a configured/prepared tree.
if [[ ! -f "${KERNELDIR}/Makefile" ]]; then
  echo "Error: ${KERNELDIR} does not look like a kernel tree (missing Makefile)" >&2
  exit 2
fi

# Autoconf is required for feature detection; it may be in generated/ or legacy location.
if [[ ! -f "${KERNELDIR}/include/generated/autoconf.h" && ! -f "${KERNELDIR}/include/linux/autoconf.h" ]]; then
  echo "Error: kernel config header not found in ${KERNELDIR}" >&2
  echo "Hint: run 'make -C ${KERNELDIR} modules_prepare' (or use a headers tree)." >&2
  exit 2
fi

JOBS="${JOBS:-$(nproc)}"

make_args=("-C" "${KERNELDIR}" "M=${MOD_DIR}")

# Headers-only trees may not provide Module.symvers/vmlinux symbol info.
# Newer kernels can treat unresolved symbols during modpost as fatal in this case.
# If kernel's Module.symvers is missing, downgrade modpost errors to warnings.
if [[ ! -f "${KERNELDIR}/Module.symvers" ]]; then
  make_args+=("KBUILD_MODPOST_WARN=1")
fi

# Pass through common cross/clang knobs only if user set them.
[[ -n "${ARCH-}" ]] && make_args+=("ARCH=${ARCH}")
[[ -n "${CROSS_COMPILE-}" ]] && make_args+=("CROSS_COMPILE=${CROSS_COMPILE}")
[[ -n "${LLVM-}" ]] && make_args+=("LLVM=${LLVM}")
[[ -n "${CC-}" ]] && make_args+=("CC=${CC}")
[[ -n "${KCFLAGS-}" ]] && make_args+=("KCFLAGS=${KCFLAGS}")
[[ -n "${EXTRA_CFLAGS-}" ]] && make_args+=("EXTRA_CFLAGS=${EXTRA_CFLAGS}")
[[ -n "${V-}" ]] && make_args+=("V=${V}")

echo "==> Building txgbe against: ${KERNELDIR}"
echo "    Module dir: ${MOD_DIR}"

# Do a clean only if requested explicitly.
if [[ "${CLEAN_FIRST-}" == "1" ]]; then
  echo "==> Cleaning module build artifacts"
  make "${make_args[@]}" clean
fi

echo "==> Building (modules)"
make "${make_args[@]}" -j"${JOBS}" modules

# Post-build checks.
KCOMPAT_HDR="${MOD_DIR}/kcompat_generated_defs.h"
KCOMPAT_STAMP="${MOD_DIR}/.kcompat_kernelsrc"
KO="${MOD_DIR}/txgbe.ko"

if [[ ! -f "${KCOMPAT_HDR}" ]]; then
  echo "Error: missing ${KCOMPAT_HDR} (kcompat generator did not run?)" >&2
  exit 3
fi
if ! grep -qE "Autogenerated for KSRC=" "${KCOMPAT_HDR}"; then
  echo "Error: ${KCOMPAT_HDR} does not contain 'Autogenerated for KSRC=' marker" >&2
  exit 3
fi

if [[ ! -f "${KCOMPAT_STAMP}" ]]; then
  echo "Warning: missing ${KCOMPAT_STAMP} (expected for KERNELDIR switch tracking)" >&2
else
  echo "==> kcompat stamp: $(cat "${KCOMPAT_STAMP}")"
fi

if [[ ! -f "${KO}" ]]; then
  echo "Error: missing ${KO} (module build failed?)" >&2
  exit 4
fi

if command -v modinfo >/dev/null 2>&1; then
  echo "==> txgbe.ko vermagic: $(modinfo -F vermagic "${KO}" || true)"
fi

echo "==> OK"
