#!/usr/bin/env bash
set -Eeuo pipefail

# Verify that kcompat_generated_defs.h and .kcompat_kernelsrc track KERNELDIR
# switches (the classic 'sticky kcompat' failure mode).
#
# Usage:
#   tools/verify_kcompat_switch.sh /path/to/kernelA /path/to/kernelB
#
# Environment:
#   ARCH, CROSS_COMPILE, LLVM, CC, KCFLAGS, EXTRA_CFLAGS, V, JOBS

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
MOD_DIR="${REPO_ROOT}/src"

K1="${1:-}"
K2="${2:-}"
if [[ -z "${K1}" || -z "${K2}" ]]; then
  echo "Usage: $0 /path/to/kernelA /path/to/kernelB" >&2
  exit 2
fi

BUILD_ONE="${SCRIPT_DIR}/build_one.sh"

stamp_file="${MOD_DIR}/.kcompat_kernelsrc"
hdr_file="${MOD_DIR}/kcompat_generated_defs.h"

# Start from a clean state once (using kernel A), then do *switch builds* without clean.
CLEAN_FIRST=1 "${BUILD_ONE}" "${K1}"

stamp1="$(cat "${stamp_file}" 2>/dev/null || true)"
hdr1="$(grep -E "Autogenerated for KSRC=" "${hdr_file}" | head -n1 || true)"

CLEAN_FIRST=0 "${BUILD_ONE}" "${K2}"

stamp2="$(cat "${stamp_file}" 2>/dev/null || true)"
hdr2="$(grep -E "Autogenerated for KSRC=" "${hdr_file}" | head -n1 || true)"

CLEAN_FIRST=0 "${BUILD_ONE}" "${K1}"

stamp3="$(cat "${stamp_file}" 2>/dev/null || true)"
hdr3="$(grep -E "Autogenerated for KSRC=" "${hdr_file}" | head -n1 || true)"

echo ""
echo "==> Switch tracking summary"
echo "  build#1 (K1): stamp='${stamp1}'"
echo "               hdr='${hdr1}'"
echo "  build#2 (K2): stamp='${stamp2}'"
echo "               hdr='${hdr2}'"
echo "  build#3 (K1): stamp='${stamp3}'"
echo "               hdr='${hdr3}'"

echo ""
if [[ -n "${stamp1}" && -n "${stamp2}" && "${stamp1}" != "${stamp2}" ]]; then
  echo "OK: stamp changes when switching kernels (K1 -> K2)"
else
  echo "WARN: stamp did not change for K1 -> K2 (are K1 and K2 the same kernel tree?)" >&2
fi

if [[ -n "${stamp1}" && -n "${stamp3}" && "${stamp1}" == "${stamp3}" ]]; then
  echo "OK: stamp returns to original value when switching back (K2 -> K1)"
else
  echo "WARN: stamp did not return to original value for K2 -> K1" >&2
fi

# The header marker must always exist.
if [[ -z "${hdr1}" || -z "${hdr2}" || -z "${hdr3}" ]]; then
  echo "Error: missing 'Autogenerated for KSRC=' marker in kcompat_generated_defs.h" >&2
  exit 3
fi

echo "==> Done"
